version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d

  web:
    image: node:lts
    # run as root so npm can write node_modules in the mounted repo
    user: root
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
      # anonymous volume for node_modules to avoid host permission issues
      - /repository/node_modules
    # install dependencies on startup, then start the app
    command: sh -c "npm install && npm start" #TODO: change the command to `npm run testandrun` to run mocha

volumes:
  group-project:
